---
development:
  # Infrastructure
  API_HOST: http://localhost:9090
  
test:
  # Application
  APP_HOST: http://localhost:9000
  # Infrastructure
  API_HOST: http://localhost:9090

app_test:
  # Application
  APP_HOST: http://localhost:9000
  # Infrastructure
  API_HOST: http://localhost:9090
  
production:
  # Infrastructure
  API_HOST: https://youtubetrendingmap-api.herokuapp.com
